/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./omlx_web/templates/**/*.html",
    "./omlx_web/static/js/**/*.js",
  ],
  safelist: [
    "sm:grid-cols-2",  // dynamic :class in _modal_model_settings.html
    "max-w-[90rem]", "max-w-[100rem]", "max-w-none",  // dashboardWidthClass in dashboard_layout.js
    "bg-emerald-500", "text-white", "border-emerald-500",
    "bg-emerald-50", "text-emerald-700", "border-emerald-200", "hover:bg-emerald-100",
  ],
  theme: {
    extend: {
      // The caption step below text-xs (see docs/web-ui-design.md).
      fontSize: {
        caption: '10px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      // Tailwind's palette resolves through the tokens in static/css/theme.css.
      colors: {
        white: 'rgb(var(--palette-white) / <alpha-value>)',
        black: 'rgb(var(--palette-black) / <alpha-value>)',
        gray: {
          50: 'rgb(var(--palette-gray-50) / <alpha-value>)',
          100: 'rgb(var(--palette-gray-100) / <alpha-value>)',
          200: 'rgb(var(--palette-gray-200) / <alpha-value>)',
          300: 'rgb(var(--palette-gray-300) / <alpha-value>)',
          400: 'rgb(var(--palette-gray-400) / <alpha-value>)',
          500: 'rgb(var(--palette-gray-500) / <alpha-value>)',
          600: 'rgb(var(--palette-gray-600) / <alpha-value>)',
          700: 'rgb(var(--palette-gray-700) / <alpha-value>)',
          800: 'rgb(var(--palette-gray-800) / <alpha-value>)',
          900: 'rgb(var(--palette-gray-900) / <alpha-value>)',
          950: 'rgb(var(--palette-gray-950) / <alpha-value>)',
        },
        neutral: {
          50: 'rgb(var(--palette-neutral-50) / <alpha-value>)',
          100: 'rgb(var(--palette-neutral-100) / <alpha-value>)',
          200: 'rgb(var(--palette-neutral-200) / <alpha-value>)',
          300: 'rgb(var(--palette-neutral-300) / <alpha-value>)',
          400: 'rgb(var(--palette-neutral-400) / <alpha-value>)',
          500: 'rgb(var(--palette-neutral-500) / <alpha-value>)',
          600: 'rgb(var(--palette-neutral-600) / <alpha-value>)',
          700: 'rgb(var(--palette-neutral-700) / <alpha-value>)',
          800: 'rgb(var(--palette-neutral-800) / <alpha-value>)',
          900: 'rgb(var(--palette-neutral-900) / <alpha-value>)',
          950: 'rgb(var(--palette-neutral-950) / <alpha-value>)',
        },
        red: {
          50: 'rgb(var(--palette-red-50) / <alpha-value>)',
          100: 'rgb(var(--palette-red-100) / <alpha-value>)',
          200: 'rgb(var(--palette-red-200) / <alpha-value>)',
          300: 'rgb(var(--palette-red-300) / <alpha-value>)',
          400: 'rgb(var(--palette-red-400) / <alpha-value>)',
          500: 'rgb(var(--palette-red-500) / <alpha-value>)',
          600: 'rgb(var(--palette-red-600) / <alpha-value>)',
          700: 'rgb(var(--palette-red-700) / <alpha-value>)',
          800: 'rgb(var(--palette-red-800) / <alpha-value>)',
          900: 'rgb(var(--palette-red-900) / <alpha-value>)',
          950: 'rgb(var(--palette-red-950) / <alpha-value>)',
        },
        orange: {
          50: 'rgb(var(--palette-orange-50) / <alpha-value>)',
          100: 'rgb(var(--palette-orange-100) / <alpha-value>)',
          200: 'rgb(var(--palette-orange-200) / <alpha-value>)',
          300: 'rgb(var(--palette-orange-300) / <alpha-value>)',
          400: 'rgb(var(--palette-orange-400) / <alpha-value>)',
          500: 'rgb(var(--palette-orange-500) / <alpha-value>)',
          600: 'rgb(var(--palette-orange-600) / <alpha-value>)',
          700: 'rgb(var(--palette-orange-700) / <alpha-value>)',
          800: 'rgb(var(--palette-orange-800) / <alpha-value>)',
          900: 'rgb(var(--palette-orange-900) / <alpha-value>)',
          950: 'rgb(var(--palette-orange-950) / <alpha-value>)',
        },
        amber: {
          50: 'rgb(var(--palette-amber-50) / <alpha-value>)',
          100: 'rgb(var(--palette-amber-100) / <alpha-value>)',
          200: 'rgb(var(--palette-amber-200) / <alpha-value>)',
          300: 'rgb(var(--palette-amber-300) / <alpha-value>)',
          400: 'rgb(var(--palette-amber-400) / <alpha-value>)',
          500: 'rgb(var(--palette-amber-500) / <alpha-value>)',
          600: 'rgb(var(--palette-amber-600) / <alpha-value>)',
          700: 'rgb(var(--palette-amber-700) / <alpha-value>)',
          800: 'rgb(var(--palette-amber-800) / <alpha-value>)',
          900: 'rgb(var(--palette-amber-900) / <alpha-value>)',
          950: 'rgb(var(--palette-amber-950) / <alpha-value>)',
        },
        green: {
          50: 'rgb(var(--palette-green-50) / <alpha-value>)',
          100: 'rgb(var(--palette-green-100) / <alpha-value>)',
          200: 'rgb(var(--palette-green-200) / <alpha-value>)',
          300: 'rgb(var(--palette-green-300) / <alpha-value>)',
          400: 'rgb(var(--palette-green-400) / <alpha-value>)',
          500: 'rgb(var(--palette-green-500) / <alpha-value>)',
          600: 'rgb(var(--palette-green-600) / <alpha-value>)',
          700: 'rgb(var(--palette-green-700) / <alpha-value>)',
          800: 'rgb(var(--palette-green-800) / <alpha-value>)',
          900: 'rgb(var(--palette-green-900) / <alpha-value>)',
          950: 'rgb(var(--palette-green-950) / <alpha-value>)',
        },
        emerald: {
          50: 'rgb(var(--palette-emerald-50) / <alpha-value>)',
          100: 'rgb(var(--palette-emerald-100) / <alpha-value>)',
          200: 'rgb(var(--palette-emerald-200) / <alpha-value>)',
          300: 'rgb(var(--palette-emerald-300) / <alpha-value>)',
          400: 'rgb(var(--palette-emerald-400) / <alpha-value>)',
          500: 'rgb(var(--palette-emerald-500) / <alpha-value>)',
          600: 'rgb(var(--palette-emerald-600) / <alpha-value>)',
          700: 'rgb(var(--palette-emerald-700) / <alpha-value>)',
          800: 'rgb(var(--palette-emerald-800) / <alpha-value>)',
          900: 'rgb(var(--palette-emerald-900) / <alpha-value>)',
          950: 'rgb(var(--palette-emerald-950) / <alpha-value>)',
        },
        teal: {
          50: 'rgb(var(--palette-teal-50) / <alpha-value>)',
          100: 'rgb(var(--palette-teal-100) / <alpha-value>)',
          200: 'rgb(var(--palette-teal-200) / <alpha-value>)',
          300: 'rgb(var(--palette-teal-300) / <alpha-value>)',
          400: 'rgb(var(--palette-teal-400) / <alpha-value>)',
          500: 'rgb(var(--palette-teal-500) / <alpha-value>)',
          600: 'rgb(var(--palette-teal-600) / <alpha-value>)',
          700: 'rgb(var(--palette-teal-700) / <alpha-value>)',
          800: 'rgb(var(--palette-teal-800) / <alpha-value>)',
          900: 'rgb(var(--palette-teal-900) / <alpha-value>)',
          950: 'rgb(var(--palette-teal-950) / <alpha-value>)',
        },
        cyan: {
          50: 'rgb(var(--palette-cyan-50) / <alpha-value>)',
          100: 'rgb(var(--palette-cyan-100) / <alpha-value>)',
          200: 'rgb(var(--palette-cyan-200) / <alpha-value>)',
          300: 'rgb(var(--palette-cyan-300) / <alpha-value>)',
          400: 'rgb(var(--palette-cyan-400) / <alpha-value>)',
          500: 'rgb(var(--palette-cyan-500) / <alpha-value>)',
          600: 'rgb(var(--palette-cyan-600) / <alpha-value>)',
          700: 'rgb(var(--palette-cyan-700) / <alpha-value>)',
          800: 'rgb(var(--palette-cyan-800) / <alpha-value>)',
          900: 'rgb(var(--palette-cyan-900) / <alpha-value>)',
          950: 'rgb(var(--palette-cyan-950) / <alpha-value>)',
        },
        sky: {
          50: 'rgb(var(--palette-sky-50) / <alpha-value>)',
          100: 'rgb(var(--palette-sky-100) / <alpha-value>)',
          200: 'rgb(var(--palette-sky-200) / <alpha-value>)',
          300: 'rgb(var(--palette-sky-300) / <alpha-value>)',
          400: 'rgb(var(--palette-sky-400) / <alpha-value>)',
          500: 'rgb(var(--palette-sky-500) / <alpha-value>)',
          600: 'rgb(var(--palette-sky-600) / <alpha-value>)',
          700: 'rgb(var(--palette-sky-700) / <alpha-value>)',
          800: 'rgb(var(--palette-sky-800) / <alpha-value>)',
          900: 'rgb(var(--palette-sky-900) / <alpha-value>)',
          950: 'rgb(var(--palette-sky-950) / <alpha-value>)',
        },
        blue: {
          50: 'rgb(var(--palette-blue-50) / <alpha-value>)',
          100: 'rgb(var(--palette-blue-100) / <alpha-value>)',
          200: 'rgb(var(--palette-blue-200) / <alpha-value>)',
          300: 'rgb(var(--palette-blue-300) / <alpha-value>)',
          400: 'rgb(var(--palette-blue-400) / <alpha-value>)',
          500: 'rgb(var(--palette-blue-500) / <alpha-value>)',
          600: 'rgb(var(--palette-blue-600) / <alpha-value>)',
          700: 'rgb(var(--palette-blue-700) / <alpha-value>)',
          800: 'rgb(var(--palette-blue-800) / <alpha-value>)',
          900: 'rgb(var(--palette-blue-900) / <alpha-value>)',
          950: 'rgb(var(--palette-blue-950) / <alpha-value>)',
        },
        indigo: {
          50: 'rgb(var(--palette-indigo-50) / <alpha-value>)',
          100: 'rgb(var(--palette-indigo-100) / <alpha-value>)',
          200: 'rgb(var(--palette-indigo-200) / <alpha-value>)',
          300: 'rgb(var(--palette-indigo-300) / <alpha-value>)',
          400: 'rgb(var(--palette-indigo-400) / <alpha-value>)',
          500: 'rgb(var(--palette-indigo-500) / <alpha-value>)',
          600: 'rgb(var(--palette-indigo-600) / <alpha-value>)',
          700: 'rgb(var(--palette-indigo-700) / <alpha-value>)',
          800: 'rgb(var(--palette-indigo-800) / <alpha-value>)',
          900: 'rgb(var(--palette-indigo-900) / <alpha-value>)',
          950: 'rgb(var(--palette-indigo-950) / <alpha-value>)',
        },
        violet: {
          50: 'rgb(var(--palette-violet-50) / <alpha-value>)',
          100: 'rgb(var(--palette-violet-100) / <alpha-value>)',
          200: 'rgb(var(--palette-violet-200) / <alpha-value>)',
          300: 'rgb(var(--palette-violet-300) / <alpha-value>)',
          400: 'rgb(var(--palette-violet-400) / <alpha-value>)',
          500: 'rgb(var(--palette-violet-500) / <alpha-value>)',
          600: 'rgb(var(--palette-violet-600) / <alpha-value>)',
          700: 'rgb(var(--palette-violet-700) / <alpha-value>)',
          800: 'rgb(var(--palette-violet-800) / <alpha-value>)',
          900: 'rgb(var(--palette-violet-900) / <alpha-value>)',
          950: 'rgb(var(--palette-violet-950) / <alpha-value>)',
        },
        purple: {
          50: 'rgb(var(--palette-purple-50) / <alpha-value>)',
          100: 'rgb(var(--palette-purple-100) / <alpha-value>)',
          200: 'rgb(var(--palette-purple-200) / <alpha-value>)',
          300: 'rgb(var(--palette-purple-300) / <alpha-value>)',
          400: 'rgb(var(--palette-purple-400) / <alpha-value>)',
          500: 'rgb(var(--palette-purple-500) / <alpha-value>)',
          600: 'rgb(var(--palette-purple-600) / <alpha-value>)',
          700: 'rgb(var(--palette-purple-700) / <alpha-value>)',
          800: 'rgb(var(--palette-purple-800) / <alpha-value>)',
          900: 'rgb(var(--palette-purple-900) / <alpha-value>)',
          950: 'rgb(var(--palette-purple-950) / <alpha-value>)',
        },
        pink: {
          50: 'rgb(var(--palette-pink-50) / <alpha-value>)',
          100: 'rgb(var(--palette-pink-100) / <alpha-value>)',
          200: 'rgb(var(--palette-pink-200) / <alpha-value>)',
          300: 'rgb(var(--palette-pink-300) / <alpha-value>)',
          400: 'rgb(var(--palette-pink-400) / <alpha-value>)',
          500: 'rgb(var(--palette-pink-500) / <alpha-value>)',
          600: 'rgb(var(--palette-pink-600) / <alpha-value>)',
          700: 'rgb(var(--palette-pink-700) / <alpha-value>)',
          800: 'rgb(var(--palette-pink-800) / <alpha-value>)',
          900: 'rgb(var(--palette-pink-900) / <alpha-value>)',
          950: 'rgb(var(--palette-pink-950) / <alpha-value>)',
        },
        rose: {
          50: 'rgb(var(--palette-rose-50) / <alpha-value>)',
          100: 'rgb(var(--palette-rose-100) / <alpha-value>)',
          200: 'rgb(var(--palette-rose-200) / <alpha-value>)',
          300: 'rgb(var(--palette-rose-300) / <alpha-value>)',
          400: 'rgb(var(--palette-rose-400) / <alpha-value>)',
          500: 'rgb(var(--palette-rose-500) / <alpha-value>)',
          600: 'rgb(var(--palette-rose-600) / <alpha-value>)',
          700: 'rgb(var(--palette-rose-700) / <alpha-value>)',
          800: 'rgb(var(--palette-rose-800) / <alpha-value>)',
          900: 'rgb(var(--palette-rose-900) / <alpha-value>)',
          950: 'rgb(var(--palette-rose-950) / <alpha-value>)',
        },
        surface: {
          DEFAULT: 'var(--bg-primary)',
          alt: 'var(--bg-secondary)',
          muted: 'var(--bg-tertiary)',
        },
        fg: {
          DEFAULT: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          tertiary: 'var(--text-tertiary)',
          muted: 'var(--text-muted)',
        },
        line: {
          DEFAULT: 'var(--border-faint)',
          strong: 'var(--border-normal)',
        },
        accent: {
          DEFAULT: 'var(--btn-primary)',
          hover: 'var(--btn-primary-hover)',
          fg: 'var(--btn-primary-text)',
        },
        danger: {
          DEFAULT: 'var(--text-danger)',
          bg: 'var(--bg-danger-hover)',
        },
        code: 'var(--code-bg)',
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.5s ease-out forwards',
      },
      keyframes: {
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'none' },
        }
      }
    },
  },
  plugins: [],
}
